### ISSUE TITLE
Check this new merged repo is OK

### ISSUE THREAD

**Issue by wdenton** [guerrilla-archiving/epa-eis#2]
I put all the EIS work into one new repo. I preserved all the histories, and I hope everything is OK.

**Comment by wdenton** [comment]
Forgot to say: there are two stage 2s here. I forget how things were going at the table---are both needed as is, or are they doing slightly different things?

**Comment by mbonsma** [comment]
It looks like both stage 2s are doing essentially the same thing - [2a](https://github.com/guerrilla-archiving/epa-eis/tree/master/2.a-scrape-metadata) outputs to a JSON with pdf links, and [2b](https://github.com/guerrilla-archiving/epa-eis/tree/master/2.b-scrape-metadata) outputs to a CSV. The other difference is that 2b creates a single CSV for all the IDs it gets, and it looks like 2a creates a separate JSON for each ID. It also looks like 2a is more complete, since 2b doesn't include pdf links (although it could be modified to).

Which one to keep would depend on which format works better I guess. But if it doesn't matter, then I think 2a did a better job.

**Comment by titaniumbones** [comment]
@ates has been asking a similar, but more general question on #guerrilla-scraping in slack. Maybe you guys can all discuss together there? 

Madeleine Bonsma writes:

> It looks like both stage 2s are doing essentially the same thing - [2a](https://github.com/guerrilla-archiving/epa-eis/tree/master/2.a-scrape-metadata) outputs to a JSON with pdf links, and [2b](https://github.com/guerrilla-archiving/epa-eis/tree/master/2.b-scrape-metadata) outputs to a CSV. The other difference is that 2b creates a single CSV for all the IDs it gets, and it looks like 2a creates a separate JSON for each ID. It also looks like 2a is more complete, since 2b doesn't include pdf links (although it could be modified to).
>
> Which one to keep would depend on which format works better I guess. But if it doesn't matter, then I think 2a did a better job.


--

**Comment by atesgoral** [comment]
My two cents regarding standardizing on an output format for the wider guerrilla archiving community:

1. Mitigation of risk of cutting corners (a fringe, social angle)

CSV is prone to formatting and parsing errors due to the fact that it is a simple format and arouses the temptation in programmers to just concatenate or split strings. However, a fully RFC-4180-compliant formatter or parser takes a bit more effort than simple string manipulation and it is wise to use a mature and trusted library to do the formatting or parsing.

Since JSON is a bit messier to format and parse using simple string manipulation, my hypothesis is that programmers are more likely to use an existing JSON library to do the formatting and parsing to begin with.

2. Expressiveness

JSON is much more expressive than CSV since there are more primitive data types than just strings. Also, JSON can have nested data structures!

3. One JSON to rule them all?

Individual JSON files for each resource might be an overkill. Per scraped page, a single JSON file to hold metadata + links to all downloadable content on the page might be better.

That could be done with a top-level JSON array of objects (`[{ ... }, { ... }]`) or maybe even as [JSON Lines](http://jsonlines.org/).

**Comment by wdenton** [comment]
I moved 2a to be 2, and moved 2b out of the way. (Generous of you, @mbonsma.) 

I also updated the docs so now all the stages are set out and it should (in theory!) all work, but stage 2 throws a lot of warnings and then dies with "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory." @mi-lee, can you check what's going on?

**Comment by sonalranjit** [comment]
@wdenton i ran 2 (@mi-lee node app), i did get a lot of warnings but most are error messages saying are you sure the link is valid or not. in total the app scraped 641 pages. couldn't recreate your issue

**Comment by mi-lee** [comment]
@wdenton Wasn't able to reproduce your error, but looking at related links like http://stackoverflow.com/questions/26094420/fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory I'm guessing the little script I hacked wasn't meant to be scraping thousands of links. I'll be looking into https://github.com/guerrilla-archiving/epa-eis/issues/4 more closely.

**Comment by mi-lee** [comment]
Pushed a fix for errors on Stage 2 here: https://github.com/guerrilla-archiving/epa-eis/pull/5 please feel free to review it. 

(Also apologies if I'm unresponsive, I'm currently on vacation 🏖)

**Comment by dcwalk** [comment]
Just checking in on the status of this issue: It looks like enough review has happened to close, or is there something that still needs to be addressed @wdenton?

**Comment by wdenton** [comment]
I think everything's covered, or in the other issue still open.
